#+title: Emacs Literate Ontology Tool (ELOT)

* What
This repository contains a template for writing OWL ontologies as
org-mode documents, with supporting functions and scripts.

Started 2024-03-03, this is work in progress and likely not to work in
any predictable fashion -- yet!

Check out the file `pizza.org` for an example ELOT file.

* Prerequisites
You should install [[http://robot.obolibrary.org/][ROBOT]] to have Turtle output; [[https://plantuml.com/][PlantUML]] and [[https://github.com/VladimirAlexiev/rdf2rml][rdfpuml]]
for diagrams.

* Quick start (needs update!)

For a minimal check that ontology can be exported and documents can be
produced:
 - Use a recent Emacs version (current latest version is 29.2)
 - Look at the init file [[elot-init.el]] for settings
 - Open a new org file, insert template =<oh= and press Tab for document
   header, insert template =<os= and press Tab for ontology skeleton.
 - Export to ontology by M-x /org-babel-tangle/, keybinding
   =C-c C-v t=. Open the ontology in Protégé to check it's OK.
 - Export to a document by M-x /org-export-dispatch/, keybinding =C-c
   C-e=. Choose your format from the menu.
