// src/debug-ast.ts
//
// Debugging utility to print the raw orgize WASM parse result for an Org file.
// Usage: npx tsx src/debug-ast.ts <input.org>

import { readFileSync } from "fs";
import { resolve } from "path";

// @ts-ignore — generated by wasm-pack
import { parse_org_to_elot } from "./wasm/elot_orgize.js";

function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error("Usage: npx tsx src/debug-ast.ts <input.org>");
    process.exit(1);
  }

  const inputPath = resolve(args[0]);
  const orgText = readFileSync(inputPath, "utf-8");

  // Parse Org via orgize WASM → raw JSON
  const json = parse_org_to_elot(orgText);
  const tree = JSON.parse(json);

  // Print the full AST as JSON
  console.log(JSON.stringify(tree, null, 2));
}

main();
