// src/parseOrgWasm.ts
//
// Thin integration layer between the orgize WASM parser and the
// ElotNode pipeline. Calls parse_org_to_elot() from the Rust/WASM
// crate and maps the resulting JSON into the TypeScript ElotNode type,
// adding rdf:type inference and automatic rdfs:label insertion.

import type { ElotNode, DescriptionItem, PrefixEntry } from "./types.js";
import { ID_SUFFIX_TO_TYPE } from "./types.js";
import { entityFromHeader } from "./entityFromHeader.js";
import { buildPrefixMap } from "./prefixes.js";

// The WASM module is generated by wasm-pack into src/wasm/.
// At build time esbuild bundles it; at dev time tsx resolves it.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated by wasm-pack, no .d.ts
import { parse_org_to_elot } from "./wasm/elot_orgize.js";

// --- Raw JSON types from the Rust crate --------------------------

/** Shape returned by the Rust crate's serde serialization. */
interface RawNode {
  level: number;
  title: string;
  tags: string[];
  id?: string;
  elotContextType?: string;
  elotContextLocalname?: string;
  elotDefaultPrefix?: string;
  resourcedefs: boolean;
  prefixdefs: boolean;
  tangleTargetOmn?: string;
  prefixes: Array<{ prefix: string; uri: string }>;
  descriptions: Array<RawDescription>;
  omnSrcBlocks: string[];
  children: RawNode[];
}

interface RawDescription {
  tag: string;
  value: string;
  meta?: RawDescription[];
}

// --- rdf:type inference from ancestor :ID: suffix ----------------

function rdfTypeFromId(id: string | null): string | null {
  if (!id) return null;
  for (const [suffix, rdfType] of Object.entries(ID_SUFFIX_TO_TYPE)) {
    if (id.endsWith(suffix)) return rdfType;
  }
  if (id.endsWith("-ontology-declaration")) return "owl:Ontology";
  return null;
}

// --- Map raw JSON to ElotNode ------------------------------------

function mapDescriptions(raw: RawDescription[]): DescriptionItem[] {
  return raw.map((d) => ({
    tag: d.tag,
    value: d.value,
    ...(d.meta && d.meta.length > 0 ? { meta: mapDescriptions(d.meta) } : {}),
  }));
}

/**
 * Recursively map a RawNode (from Rust JSON) into an ElotNode,
 * enriching it with:
 *   - uri / label from entityFromHeader()
 *   - rdfType inherited from ancestor :ID: suffixes
 *   - automatic rdf:type and rdfs:label description items
 */
function mapRawNode(
  raw: RawNode,
  parentRdfType: string | null,
): ElotNode {
  // Determine entity identity from the heading title
  let uri: string | null = null;
  let label: string | null = null;
  const tags = raw.tags ?? [];
  const isNodeclare = tags.includes("nodeclare");

  if (!isNodeclare) {
    const entity = entityFromHeader(raw.title);
    if (entity) {
      uri = entity.id;
      label = entity.label;
    }
  }
  if (uri && !label) label = uri;

  // Determine rdfType
  let rdfType: string | null = null;
  const id = raw.id ?? null;
  if (id && (raw.resourcedefs || id.endsWith("-ontology-declaration"))) {
    rdfType = rdfTypeFromId(id);
  }
  if (!rdfType && parentRdfType) {
    rdfType = parentRdfType;
  }

  // Map prefixes
  const prefixes: PrefixEntry[] = (raw.prefixes ?? []).map((p) => ({
    prefix: p.prefix,
    uri: p.uri,
  }));

  // Map raw descriptions and add automatic entries
  const rawDesc = mapDescriptions(raw.descriptions ?? []);
  const descriptions: DescriptionItem[] = [];

  const hasExplicitType = rawDesc.some((d) => d.tag === "rdf:type");
  if (uri && rdfType && !hasExplicitType) {
    descriptions.push({ tag: "rdf:type", value: rdfType });
  }
  if (uri && label && label !== uri) {
    const hasLabel = rawDesc.some((d) => d.tag === "rdfs:label");
    if (!hasLabel) descriptions.push({ tag: "rdfs:label", value: label });
  }
  descriptions.push(...rawDesc);

  // Recursively map children
  const children = (raw.children ?? []).map((child) => mapRawNode(child, rdfType));

  const result: ElotNode = {
    level: raw.level,
    title: raw.title,
  };
  if (tags.length > 0) result.tags = tags;
  if (uri) result.uri = uri;
  if (label) result.label = label;
  if (rdfType) result.rdfType = rdfType;
  if (raw.id) result.id = raw.id;
  if (raw.elotContextType) result.elotContextType = raw.elotContextType;
  if (raw.elotContextLocalname) result.elotContextLocalname = raw.elotContextLocalname;
  if (raw.elotDefaultPrefix) result.elotDefaultPrefix = raw.elotDefaultPrefix;
  if (raw.resourcedefs) result.resourcedefs = true;
  if (raw.prefixdefs) result.prefixdefs = true;
  if (raw.tangleTargetOmn) result.tangleTargetOmn = raw.tangleTargetOmn;
  if (prefixes.length > 0) result.prefixes = prefixes;
  if (descriptions.length > 0) result.descriptions = descriptions;
  if ((raw.omnSrcBlocks ?? []).length > 0) result.omnSrcBlocks = raw.omnSrcBlocks;
  if (children.length > 0) result.children = children;

  return result;

}

// --- Public API --------------------------------------------------

/**
 * Parse an Org-mode string into an ElotNode tree.
 *
 * Uses the orgize WASM parser (Rust compiled to WebAssembly) to extract
 * the Org structure, then enriches it with OWL entity identity, rdf:type
 * inference, and automatic annotation insertion.
 *
 * This replaces the old orga-based parseHierarchy + parseOrg pipeline.
 */
export function parseOrg(orgText: string): ElotNode {
  const json: string = parse_org_to_elot(orgText);
  const raw: RawNode = JSON.parse(json);

  // The raw root is a level-0 "ROOT" node. Map its children.
  const children = (raw.children ?? []).map((child) => mapRawNode(child, null));
  const root: ElotNode = {
    level: 0,
    title: "ROOT",
  };
  if (children.length > 0) root.children = children;

  return root;
}

/**
 * Find the global prefix map from the hierarchy.
 * Iterative to avoid call-stack overflow.
 */
export function getPrefixMap(root: ElotNode): Map<string, string> | null {
  const stack: ElotNode[] = [root];
  while (stack.length > 0) {
    const node = stack.pop()!;
    if (node.prefixdefs && (node.prefixes ?? []).length > 0) {
      return buildPrefixMap(node.prefixes!);
    }
    const children = node.children ?? [];
    for (let i = children.length - 1; i >= 0; i--) {
      stack.push(children[i]);
    }
  }
  return null;
}

/**
 * Collect all omn src blocks from the ElotNode tree.
 * These were extracted by the Rust parser from #+begin_src omn blocks.
 */
export function collectOmnSrcBlocks(root: ElotNode): string[] {
  const blocks: string[] = [];
  const stack: ElotNode[] = [root];
  while (stack.length > 0) {
    const node = stack.pop()!;
    if (node.omnSrcBlocks) {
      blocks.push(...node.omnSrcBlocks);
    }
    // Push children in reverse so we get document order
    const children = node.children ?? [];
    for (let i = children.length - 1; i >= 0; i--) {
      stack.push(children[i]);
    }
  }
  return blocks;
}
