#+title: ELOT documentation

* More documentation is needed

 - installation
 - simple use -- editing and exporting an ontology
 - typical use cases
 - advanced use
   - including illustrations
   - exporting to formats other than HTML
   - including SPARQL queries and generating diagrams
   - reporting and QA
   - use in a "modular" ontology with various imports
   - integrating templates for generated ontology content

* Introductory presentation, 2024

Together with Vladimir Alexiev and Melinda Hodkiewicz, Johan W. Klüwer presented ELOT to the 2024-05-31 online meeting of the Industrial Ontology Foundry's Technical Oversight Board.
This presentation can be a good starting point for a quick look at main features as well as the motivations behind the tool.
 - [[file:20240525T181908--elot-presented-to-iof-tob__elot_emacs_iof.html][Presentation slides in HTML format]]

* Installation

For Windows users who don't have the Emacs editor installed, [[file:readme_installation.md]] (2024) documents how to get started. This walkthrough is however unfinished.
